Vue/Models/ErrorViewModel.cs
using System;

namespace Vue.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Vue/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Vue.Controllers
{
    public class BookController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Test()
        {
            return View();
        }
    }
}

Vue/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Vue.Models;

namespace Vue.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult Test()
        {
            return View();
        }

        // 基礎範例
        public IActionResult BasicExample()
        {
            return View();
        }

        // 模板語法
        public IActionResult TemplateSyntax()
        {
            return View();
        }

        // 計算屬性和偵聽器
        public IActionResult CalculationPropertie()
        {
            return View();
        }

        // Class與Style綁定
        public IActionResult ClassAndStyleBinding()
        {
            return View();
        }

        // 條件渲染
        public IActionResult ConditionalRendering()
        {
            return View();
        }

        // 列表渲染
        public IActionResult ListRendering()
        {
            return View();
        }

        // 事件處理
        public IActionResult EventProcessing()
        {
            return View();
        }

        // 表單輸入綁定
        public IActionResult FormInputBinding()
        {
            return View();
        }

        // 組件基礎
        public IActionResult ComponentBasis()
        {
            return View();
        }
    }
}

Vue/Controllers/OrganizeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Vue.Controllers
{
    public class OrganizeController : Controller
    {
        public IActionResult OrganizeTemplate()
        {
            return View();
        }

        public IActionResult OrganizeTemplate2()
        {
            return View();
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Template()
        {
            return View();
        }

        public IActionResult Template1()
        {
            return View();
        }

        public IActionResult Template2()
        {
            return View();
        }

        public IActionResult Template3()
        {
            return View();
        }

        public IActionResult Template4()
        {
            return View();
        }

        public IActionResult Template5()
        {
            return View();
        }

        public IActionResult Template6()
        {
            return View();
        }

        public IActionResult Step()
        {
            return View();
        }
    }
}

Vue/Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Vue.Controllers
{
    public class ServiceController : Controller
    {
        [HttpPost]
        public IActionResult GetAnswer(string question)
        {
            if (question == "Hello?")
                return Json(true);

            return Json(false);
        }
    }
}

Vue/Views/Book/Test.cshtml
@section scripts{
    <script src="~/lib/vue.js"></script>
    <script>
        var app = new Vue({
            el: '#app',
            data: {
                value: { first: 'ray', last: 'Liang' }
            }
        })

        var project = new Vue({
            el: '#project',
            data: {
                title: "vue-todos",
                todos: [{ value: '閱讀前端', done: false, created: Date.now() }, { value: '補充範例', done: true, created: Date.now()+300000 }
                    , { value: '心得分享', done: false, created: Date.now()-300000 }]
            }
        })
    </script>
}
<div id="project">
    <h1>{{title}}</h1>
    <ul class="todos">
        <li v-for="(todo,index) in todos" :class="{'checked':todo.done}">
            {{todo.done}}
            <label>{{index+1}}.{{todo.value}}</label>
            <time>{{todo.created}}</time>
        </li>
        </ul>
</div>
<hr>
<div id="app">
    <div v-for="obj in value">
        {{obj}}
    </div>
</div>

Vue/Views/Home/BasicExample.cshtml
@{
    ViewData["Title"] = "基礎範例";
}
@section scripts{
    <script>
        var app = new Vue({
            el: '#app', // 拿app物件
            data: {
                message: 'Hello Vue!'
            }
        })

        var app2 = new Vue({
            el: '#app2',
            data: {
                title: 'vue-tdods',
                todos: [{ value: '1', done: 'A' }, { value: '2', done: 'B' }, { value: '3', done: 'C' }]
            }
        })
        app2.todos.push({ value: '魔王', done: '六翼' })  // 推資料

        var app3 = new Vue({
            el: '#app3',
            data: {
                message: 'Hello Vue! ' + new Date().toLocaleDateString()
            }
        })

        var app4 = new Vue({
            el: '#app4',
            data: {
                seen: true
            }
        })

        var app5 = new Vue({
            el: '#app5',
            data: {
                message: 'Hello 歡迎來到魔王城',
            },
            methods: { //方法要寫在裡面
                reserseMessage: function () {
                    this.message = this.message.split('').reverse().join('') // reverse把字相反
                }
            }
        })

        var app6 = new Vue({
            el: '#app6',
            data: {
                message: 'Hello 天使的世界',
                test: false
            }
        })

        // 全域變數 'todo-item' 就會等於自訂義的<div>
        Vue.component('todo-item', {
            props:['todo'],         // 陣列然後塞變數
            template: '<div>{{todo.text}}</div>' // template 他會把資料寫在content 一定要加div之類的
                                                 // 因為知道todo塞的資料是有text才可以這樣寫
        })

        var app7 = new Vue({
            el: '#app7',
            data: {
                groceryList: [
                    { id: 0, text: '莫欺' },
                    { id: 1, text: '少年' },
                    { id: 2, text: '窮' }
                ]
            }
        })
    </script>
}
<div id="app">
    {{ message }}
</div>
<hr>
<div id="app2">
    {{title}}  @*data title*@
    <div v-for="todo in todos">
        @*data todos 前面的todo是陣列元素別名，todos是真正的陣列(在app2) 上面那一行*@
        {{todo.value}}{{todo.done}}        @*可以拿陣列裡面的值*@

    </div>
    <div v-for="(todo,index) in todos" :id="index">
        @*:id 將index的值放到Dom的Id屬性輸出結果為id="1" 如果沒加:就是為他指定字串*@
        @*(todos,index) 前面的todo是陣列元素別名index是第幾個陣列，todos是真正的陣列(在app2) 上面那一行(另一種寫法針對其中某個陣列)*@
        {{index+1}}.{{todo.value}}{{todo.done}}         @*可以拿陣列裡面的值*@
    </div>
</div>
<hr>
<div id="app3">
    <span v-bind:title="message">
        @*v-bind:title  可以為下面的字設定Title 要把滑鼠放在字上面才會出現*@
        這是我第一個Vue
    </span>
</div>
<hr>
<div id="app4">
    <span v-if="seen">你看不見我</span> @*Vue的if事件*@
    @*v-if 指令将根据表达式 seen 的值的真假来插入/移除 <span> 元素。*@
</div>
<hr>
<div id="app5">
    {{message}}
    <br>
    <button v-on:click="reserseMessage">把字變相反</button> @*Vue的button click事件*@
</div>
<hr>
<div id="app6">
    <p>{{message}}</p>
    <input v-model="message">  @*Vue的v-model是指可以在input輸入，並且可以雙向綁定，所以在輸入時就會改變Message的值*@
    {{test}}
    <input type="checkbox" v-model="test">
</div>
<hr>
<div id="app7">
    <todo-item v-for="item in groceryList" v-bind:todo="item" v-bind:key="item.id"></todo-item>
    @*他會先foreach groceryList 然後把item的資料bind到全域變數的todo，把item.Id的資料bind到key*@
</div>

Vue/Views/Home/CalculationPropertie.cshtml
@{ 
    ViewData["Title"] = "計算屬性和偵聽器";
}
@section scripts{
    <script src="https://cdn.jsdelivr.net/npm/axios@0.12.0/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/lodash@4.13.1/lodash.min.js"></script>
    <script>
        // 計算屬性
        var app13 = new Vue({
            el: '#app13',
            data: {
                message: 'Hello'
            },
            // 計算屬性緩存
            computed: {
                // 计算属性的 getter
                reversedMessage: function () {
                    // `this` 指向 app13 实例
                    return this.message.split('').reverse().join('')
                }
            }
        })

        //这里我们声明了一个计算属性 reversedMessage。我们提供的函数将用作属性 app13.reversedMessage 的 getter 函数：
        console.log(app13.reversedMessage) // => 'olleH'
        app13.message = 'Goodbye'
        console.log(app13.reversedMessage) // => 'eybdooG'

        // 计算属性缓存 vs 方法
        // 我们可以将同一函数定义为一个方法而不是一个计算属性。两种方式的最终结果确实是完全相同的。
        // 然而，不同的是计算属性是基于它们的依赖进行缓存的。只在相关依赖发生改变时它们才会重新求值。
        // 这就意味着只要 message 还没有发生改变，多次访问 reversedMessage 计算属性会立即返回之前的计算结果，而不必再次执行函数。
        // 所以就是說計算屬性Message沒有被改，那他不會在去呼叫會拿之前運算的結果，方法她會每一次都去跑
        var app14 = new Vue({
            el: '#app14',
            data: {
                message: 'Hello'
            },
            // 計算屬性緩存
            methods: {
                // 计算属性的 getter
                reversedMessage: function () {
                    // `this` 指向 app13 实例
                    return this.message.split('').reverse().join('')
                },
                touch: function () {
                    // `this` 指向 app13 实例
                    return this.message = "world"
                }
            },
            computed: {
                now: function () {
                    return Date.now()
                },
                reversedMessagex: function () {
                    return this.message.split('').reverse().join('')
                }
            }
        })

        var app15 = new Vue({
            el: '#app15',
            data: {
                first: 'Hello',
                last: 'Vue!'
            },
            computed: {
                fullName: {
                    // getter
                    get: function () {
                        return this.first + ' ' + this.last
                    },
                    // setter
                    set: function (newValue) {
                        var names = newValue.split(' ')
                        this.first = names[0]
                        this.last = names[names.length - 1]
                    }
                }
            },
            methods: {
                touch: function () {
                    app15.fullName = 'Winner'
                }
            }
        })

        var app16 = new Vue({
            el: '#app16',
            data: {
                question: '',
                answer: '在你問一個問題之前，我不能給你答案！'
            },
            watch: {
                // 如果 `question` 发生改变，这个函数就会运行
                question: function (newQuestion, oldQuestion) {
                    this.answer = '等你停止打字......'
                    this.getAnswer()
                    //this.debouncedGetAnswer()
                }
            },
            created: function () {
                // `_.debounce` 是一个通过 Lodash 限制操作频率的函数。
                // 在这个例子中，我们希望限制访问 yesno.wtf/api 的频率
                // AJAX 请求直到用户输入完毕才会发出。想要了解更多关于
                // `_.debounce` 函数 (及其近亲 `_.throttle`) 的知识，
                // 请参考：https://lodash.com/docs#debounce
                this.debouncedGetAnswer = _.debounce(this.getAnswer, 500)
            },
            methods: {
                getAnswer: function () {
                    if (this.question.indexOf('?') === -1) {
                        this.answer = '問題通常包含問號。'
                        return
                    }
                    this.answer = 'Thinking...'
                    $.post('/Service/GetAnswer', { question: app16.question }, function (result) {
                        if (result)
                            return app16.answer = '回答正確'
                        else
                            return app16.answer = '錯誤'
                    }, 'json');
                }
            }
        })
    </script>
}
<div id="app13">
    <p>Original message: "{{message}}"</p>
    <p>Computed reversed message:"{{reversedMessage}}"</p>
</div>
<hr />
<div id="app14">
    <p>Reversed message:"{{reversedMessage()}}"</p>
    {{now}}
    <p>Reversedx message:"{{reversedMessagex}}"</p>
    <button v-on:click="touch()">touch me</button>
</div>
<hr>
<div id="app15">
    {{fullName}}
    <button v-on:click="touch()">touch me</button>
</div>
<hr>
<div id="app16">
    <p>
        問一個是/否的問題：
        <input v-model="question">
    </p>
    <p>{{answer}}</p>
</div>

Vue/Views/Home/ClassAndStyleBinding.cshtml
@{
    ViewData["Title"] = "Class與Style綁定";
}
@section scripts{
    <script>
        // 我们可以传给 v-bind:class 一个对象，以动态地切换 class：
        //上面的语法表示 active 这个 class 存在与否将取决于数据属性 isActive 的 truthiness。
        //你可以在对象中传入更多属性来动态切换多个 class 。此外，v - bind: class 指令也可以与普通的 class 属性共存。当有如下模板:
        var data = {
            isActive: true,
            hasError: false
        }

        var data1 = {
            classObject: {
                active: true,
                'text-danger': false
            }
        }

        var app = new Vue({
            el: '#app',
            data: {
                isActive: true,
                error: null
            },
            computed: {
                classObject: function () {
                    return {
                        active: this.isActive && !this.error,
                        'text-danger': this.error && this.error.type === 'fatal'
                    }
                }
            }
        })

        var data3 = {
            activeClass: 'active',
            errorClass: 'text-danger'
        }

        Vue.component('item-component', {
            template: '<p class="foo bar">Hi</p>',
            isActive: true
        })

        var app2 = new Vue({
            el: '#app2',
            data: {
                activeColor: 'red',
                fontSize: 30
            }
        })

        var app3 = new Vue({
            el: '#app3',
            data: {
                ObjectStyle: {
                    color: 'blue',
                    fontSzie:'20px'
                }
            }
        })
    </script>
}
<div class="static" v-bind:class="{active:isActive,'text-danger:hasError'}">data</div>
@*结果渲染为：<div class="static active"></div>*@
@*当 isActive 或者 hasError 变化时，class 列表将相应地更新。
    例如，如果 hasError 的值为 true，class 列表将变为 "static active text-danger"。*@
<hr>
<div v-bind:class="classObject">data1</div>
@*渲染的结果和上面一样。我们也可以在这里绑定一个返回对象的计算属性。这是一个常用且强大的模式：*@
<hr>
<div id="app" v-bind:class="classObject">app</div>
<hr>
<p>數組語法</p>
<div v-bind:class="[activeClass,errorClass]">data3</div>
@*渲染为：<div class="active text-danger"></div>*@
@*如果你也想根据条件切换列表中的 class，可以用三元表达式：
    <div v-bind:class="[isActive ? activeClass : '', errorClass]"></div>*@
@*不过，当有多个条件 class 时这样写有些繁琐。所以在数组语法中也可以使用对象语法：
    <div v-bind:class="[{ active: isActive }, errorClass]"></div>*@
<hr>
<item-component class="baz boo"></item-component>
@*HTML 将被渲染为:<p class="foo bar baz boo">Hi</p>*@
@*对于带数据绑定 class 也同样适用：*@
<item-component v-bind:class="{active: isActive}">99</item-component>
@*当 isActive 为 true 时，HTML 将被渲染成为：<p class="foo bar active">Hi</p>*@
<hr>
<p>v-bind:style 範例</p>
<div id="app2" v-bind:style="{color:activeColor,fontSize:fontSize+'px'}">555</div>
<hr>
@*直接绑定到一个样式对象通常更好，这会让模板更清晰：*@
<div id="app3" v-bind:style="ObjectStyle">模板</div>
<hr>

Vue/Views/Home/ConditionalRendering.cshtml
@{
    ViewData["Title"] = "條件渲染";
}
@section scripts{
    <script>
        var app = new Vue({
            el: '#app',
            data: {
                value: '12345'
            },
            methods: {
                but1: function () {
                    return this.value = '12345'
                },
                but2: function () {
                    return this.value = '54321'
                },
                but3: function () {
                    return this.value = '99999'
                }
            }
        })

        var app1 = new Vue({
            el: '#app1',
            data: {
                loginType: ''
            },
            methods: {
                change: function () {
                    if (this.loginType)
                        return this.loginType = '';
                    else
                        return this.loginType = 'username'
                }
            }

        })

        var app2 = new Vue({
            el: '#app2',
            data: {
                test: true
            },
            methods: {
                change: function () {
                    if (this.test)
                        return this.test = false
                    else
                        return this.test = true
                }
            }

        })

    </script>
}
<div id="app">
    {{value}}
    <p v-if="value == '54321'">Success</p>
    <p v-else-if="value == '12345'">Error</p>
    <p v-else>Boom</p>
    <button v-on:click="but1">12345</button>
    <button v-on:click="but2">54321</button>
    <button v-on:click="but3">99999</button>
</div>
<hr>
<div id="app1">
    <template v-if="loginType === 'username'">
        <label>Username</label>
        @*設Key 就會把input的資料給清空，沒設定的話就會一直存在*@
        @*沒設定Key就會復用*@
        <input placeholder="Enter your username" key="username-input">
    </template>
    <template v-else>
        <label>Email</label>
        <input placeholder="Enter your email address" key="email-input">
    </template>
    <button v-on:click="change">切换按钮</button>
</div>
<hr>
@*v-show 只是简单地切换元素的 CSS 属性 display*@
@*v-if 是“真正”的条件渲染，因为它会确保在切换过程中条件块内的事件监听器和子组件适当地被销毁和重建。
    v-if 也是惰性的：如果在初始渲染时条件为假，则什么也不做——直到条件第一次变为真时，才会开始渲染条件块。
    相比之下，v-show 就简单得多——不管初始条件是什么，元素总是会被渲染，并且只是简单地基于 CSS 进行切换。
    一般来说，v-if 有更高的切换开销，而 v-show 有更高的初始渲染开销。因此，如果需要非常频繁地切换，则使用 v-show 较好；如果在运行时条件很少改变，则使用 v-if 较好。*@
<div id="app2">
    <h1 v-show="test">Hello</h1>
    <button v-on:click="change">切换按钮</button>
</div>
@*不推荐同时使用 v-if 和 v-for。请查阅风格指南以获取更多信息。
当 v-if 与 v-for 一起使用时，v-for 具有比 v-if 更高的优先级。请查阅列表渲染指南 以获取详细信息。*@

Vue/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p><h2>這是我的Vue學習網站</h2></p>
    <img src="~/image/62662599.jpg" />
</div>

Vue/Views/Home/Test.cshtml
@{
    ViewData["Title"] = "Test";
    Layout = "~/Views/Shared/_QunitLayout.cshtml";
}

<script>
    QUnit.test("hello test", function (assert) {
        assert.ok(1 == "1", "Passed!");
    });
</script>

Vue/Views/Home/Test2.cshtml
@section scripts{
    <script src="~/lib/vue.js"></script>
    <script>
        Vue.component('items', {
            props: ['todo'],
            template:'<div>{{todo.text}}</div>'
        })

        var test1 = new Vue({
            el: '#test1',
            data: {
                todos: [{ id: 0, text: '天' }, { id: 1, text: '地' }, { id: 2, text: '我掌握' }],
                zoos: [{ text: 'rabbit' }, { text: 'cat' }, { text: 'dog' }, {text:'ox'}]
            }
        })
    </script>
}
<div id="test1">
    <items v-for="to in todos" v-bind:todo="to" v-bind:key="to.id"></items>
    <hr>
    <items v-for="zoo in zoos" v-bind:todo="zoo"></items>
</div>

Vue/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vue</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="~/css/layout_Stylecss.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Vue</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="mynav_dropdown">
                            <button class="mynav_dropbtn">
                                練習
                                <i class="fa fa-caret-down"></i>
                            </button>
                            <div class="mynav_dropdown-content">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="BasicExample">基礎範例</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="TemplateSyntax">模板語法</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="CalculationPropertie">計算屬性和偵聽器</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ClassAndStyleBinding">Class與Style綁定</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ConditionalRendering">條件渲染</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ListRendering">列表渲染</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="EventProcessing">事件處理</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="FormInputBinding">表單輸入綁定</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ComponentBasis">組件基礎</a>
                            </div>
                        </li>
                        <li class="mynav_dropdown">
                            <button class="mynav_dropbtn">
                                整理
                                <i class="fa fa-caret-down"></i>
                            </button>
                            <div class="mynav_dropdown-content">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Organize" asp-action="Step">目錄</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Organize" asp-action="OrganizeTemplate">整理1</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Organize" asp-action="OrganizeTemplate2">整理2</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Organize" asp-action="Template">生命週期</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Organize" asp-action="Template1">[v-bind:class][v-bind:style]</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Organize" asp-action="Template2">[v-if][v-else][v-else-if][v-show]</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Organize" asp-action="Template3">[v-for]</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Organize" asp-action="Template4">[v-on]</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Organize" asp-action="Template5">[v-model]</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Organize" asp-action="Template6">[Vue.component][v-bind:is]</a>
                            </div>
                        </li>
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Vue">Vue練習</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Test2">練習</a>
                            </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Test">Quint</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">關於</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2018 - Vue - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @*<script src="~/lib/vue.js"></script>*@
    <script src="~/lib/vue2.6.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>